marp-team/marp

- .postcssrc.js
- .sassrc.js
- package.json
- src/docsify.scss
- src/index.pug
- yarn.lock
We are going to host web and JS/CSS by Netlify. It will use in common branded document of Marp family.
Parcel build is working on local correctly, but isn't working on netlify. This PR is trying to resolve this.
```
10:47:45 PM: yarn run v1.9.4
10:47:45 PM: $ yarn run --silent clean && parcel build src/*
10:47:50 PM: Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but postcss-import uses 7.0.2. Perhaps this is the source of the error below.
10:47:50 PM: 🚨  /opt/build/repo/src/docsify.scss:undefined:undefined: Failed to find 'f7a5c2b88937640a559938331eccd348.css'
10:47:50 PM:   in [
10:47:50 PM:     /opt/build/repo/src
10:47:50 PM:   ]
10:47:50 PM:   in [
10:47:50 PM:     /opt/build/repo/src
10:47:50 PM:   ]
10:47:50 PM:     at resolveModule.catch.catch …
```
> Fix error of parcel build on Netlify

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
To allow GitHub issue tracker of Marp project repos, we add contributing guideline for Marp projects in this repo.
[yhatt/marp](https://github.com/yhatt/marp/issues) has happened a confusion caused by a lot of issues because it has no guidelines about issue management. I have not responded most issues/PRs to show stopping maintenance at the legacy languages. We should avoid it in marp-team.
We are going to allow issue tracking by refer to this guideline in per projects. [Marpit](https://github.com/marp-team/marpit) would become to the first project applied this guideline.
> Add contributing guideline for Marp projects

- LICENSE
We have prepared a mail address of marp-team. It's good to use team address instead of maintainer's personal address to show LICENSE.
> Update license author to marp-team

- public/_redirects
- public/index.html
I'm trying to use the redirect setting provided by Netlify. HTML for redirect by meta may be unnecessary.
> Remove index.html and redirect to repository by Netlify directly

- README.md
Marp family section on `README.md` should be reorganized because of a lot of projects to support Marp ecosystem.
- Grouped our projects by the kind.
- I had released **[Marp for VS Code](https://github.com/marp-team/marp-vscode)**, the VS Code extension to preview Marp Markdown. **(NOTICE: available only in VSCode insiders)**
<p align="center"><a href="https://github.com/marp-team/marp-vscode"><img src="https://raw.githubusercontent.com/marp-team/marp-vscode/master/images/screenshot.png" width="500" /></a></p>
- Added components working in progress: [Marp React](https://codesandbox.io/s/kkryjmyy75) and [Marp Vue](https://2x994l3roj.codesandbox.io/). I'm trying these at my CodeSandbox.
|[Marp React example](https://codesandbox.io/s/kkryjmyy75)<br>([React 16.8: React …
> Update Marp family section on README.md

- README.md
[Marp Vue's initial release v0.0.1 was shipped.](https://www.npmjs.com/package/@marp-team/marp-vue) I've added a link to Marp Vue repository and npm badge.
> Add link to Marp Vue integration

- github-release.js
Add Marp team common script to create release on GitHub based on a version tag. We expect to use this via CI.
> Add automation script to create release on GitHub

- .github/FUNDING.yml
- README.md
Today I become a member of GitHub Sponsors beta program! This PR updates `FUNDING.yml` and prepares "Sponsors" section to show thanks for sponsors.
https://github.com/users/yhatt/sponsorship
I'm already using Patreon (yhatt/marp#266), but I would advice patrons to move into GitHub Sponsors.
> Enable GitHub Sponsors

- .circleci/config.yml
- .prettierignore
- package.json
- packages/website/package.json
- yarn.lock
This PR will upgrade dependent packages to the latest version via `yarn upgrade-interactive --latest`. It includes bumped [Marp Core v0.15.2](https://github.com/marp-team/marp-core/releases/tag/v0.15.2), used for demo slides in https://marp.app/.
- Resolves a vulnerability in `handlebars`.
- Simplified how to upgrade yarn on CI environment.
- Update Prettier settings to suit for Charge static site generator.
> Upgrade dependent packages to the latest version

- README.md
Hey all!
I was working on a tool to help deploy a Marp presentation to GitHub pages using a GitHub Action.
This has a few nice benefits:
- Manage your presentation in GitHub, just like code
- Automated deployment of a presentation to free GitHub Pages hosting
- A Marp presentation showing how to get started
If there's interest I think this is a good place to add the link.
Thanks!
> Link to Marp GitHub Action

- package.json
- packages/website/package.json
- yarn.lock
Relax resolutions for CVE-2020-7598 by bumping deep dependencies. `mkdirp`, many packages have depended, has bumped version to fix it.
~At the moment `yarn audit` complains to `minimist` v0.2.1, but actually it has [a backport of the same patch](https://github.com/substack/minimist/commit/d8f2cc97cc2569f2468ba06cdd0121290f630819) as v1.x.~ `optimist` has no longer maintained so I cannot expect much for patch.
**UPDATE**: npm advisory was fixed. https://www.npmjs.com/advisories/1179/versions
> Relax resolutions for CVE-2020-7598

- packages/website/src/index/features.js.jsx
Some octicons have broken image links by updating Octicon v10 hosted at [Icongram](https://icongr.am/octicons).
https://github.com/primer/octicons/releases/tag/v10.0.0
> Fix broken Octicons

- website/next.config.js
- website/package.json
- yarn.lock
Bumped Next.js to v10.0.4 stable.
The latest stable seems to have backed out font optimization in default setting. I've added `experimental.optimizeFonts` setting again.
> Bump Next to v10.0.4 stable

- website/package.json
- yarn.lock
Bumped Next.js to v10.0.6.
I've confirmed that font optimization is turning back to work. :smiley: We have got back inlining Google Fonts and improved performance score again. 💯
> Bump Next.js to v10.0.6

- netlify.toml
Many people hate Google's [FLoC](https://github.com/WICG/floc). Marp team should save from implicit cross-site trackings from our website visitor.
By technical reason, Marp requires Google Chrome/Chromium to convert Marp Markdown into PDF. If you want to avoid using Chrome due to FLoC, we are providing a way to use the other flavored browser such as Brave (https://brave.com/why-brave-disables-floc/) and Vivaldi (https://vivaldi.com/blog/no-google-vivaldi-users-will-not-get-floced/)
Set the path through `CHROME_PATH` env in Marp CLI, and `Markdown > Marp: Chrome Path` setting in Marp for VS Code.
> Disable FLoC

- lage.config.js
- lerna.json
- package.json
- yarn.lock
Unfortunately lerna is not actively maintained: https://github.com/lerna/lerna/issues/2703.
It did not matter in Marp because not taking monorepo architecture widely, but even so I'm worried about continously using unmaintained tool.
We're using lerna only for running tasks in every yarn workspaces. So we can replace to an alternative task runner.
Now we are trying to use [lage](https://microsoft.github.io/lage/) by Microsoft. It has a simple setting, advanced thinking about pipeline, and nice performance. In addition, lage is using Marp! :heart: (https://github.com/microsoft/lage/blob/master/decks/lage-deck.md)
> Switch task runner from unmaintained lerna to lage

- website/next-env.d.ts
- website/package.json
- yarn.lock
https://nextjs.org/blog/next-11-1
Next.js 11.1 has a security patch for CVE-2021-37699. (https://nextjs.org/blog/next-11-1#security-patch)
It is not required to change existing codes drastically. On the other hand, ESM support may be helpful to some modules. (e.g. remark parser and unified ecosystem)
> Bump Next.js to 11.1

- README.md
Hi folks,
I'm the community maintainer of a project for building Marp slides to GitHub Pages using a workflow. I've updated the repo name from the poorly named `test-marp-action` to `marp-to-pages` (plus many other needed changes). This PR updates the link.
-Robert
> marp-action renamed to marp-to-pages

- website/css/index.css
- website/pages/blog.tsx
- Fix broken RSS feed: Escape title and description of articles.
- Update `/blog` to render images with fixed width.
- Fix the scroll position when navigated page with Next.js router.
> Fix broken RSS feed due to not-escaped special entities, and more hotfixes

- website/blog/202205-ecosystem-update.md
- website/pages/_app.tsx
Update for https://marp.app/blog/202205-ecosystem-update: Describe how to opt in the new core in a VS Code extension.
> Blog article update: Opt in the new core in a VS Code extension

- website/blog/how-to-make-custom-transition.md
[Marp CLI v2.0.4](https://github.com/marp-team/marp-cli/releases/tag/v2.0.4) has allowed setting the default duration time to the custom transition.
> Update blog article of how to make custom transition
